version: "3.9"

services:

  web-notas:
    image: thomsch98/markserv
    container_name: web-notas-mike

    restart: unless-stopped

    environment:
      TZ: 'Europe/Andorra'

    ports:
      - 3080:3080
    volumes:
      - ./:/data


